# Generated by Django 4.1.3 on 2022-11-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzeNumber', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geeksmodel',
            old_name='description',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='geeksmodel',
            name='title',
        ),
        migrations.AddField(
            model_name='geeksmodel',
            name='phoneNumber',
            field=models.BigIntegerField(default=0),
        ),
    ]
