# Generated by Django 4.1.3 on 2022-11-18 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzeNumber', '0003_phonemessagemodel_delete_geeksmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonemessagemodel',
            name='new_message',
        ),
    ]
